## Temperature Conversion
You have an array of temperatures in Celsius. Use element-wise operations to convert them to Farenheit using the formula: `F = (9/5) * C + 32`

In [7]:
import numpy as np
cel = np.array([30, 27, 50, 100])
mul_factor = 9/5
base_factor = 32
mult = cel * mul_factor
faren = mult + base_factor
print(f"In Celsius: {cel}")
print(f"In Farenheit: {np.round(faren, 2)}")

In Celsius: [ 30  27  50 100]
In Farenheit: [ 86.   80.6 122.  212. ]


## Array Scaling
Create a 2D array and scale each row by a different factor. For example, scale the first row by 2, the second row by 3, and so on.

In [11]:
import numpy as np
a = np.array([[30, 27],
             [50, 100]
             ])
scaling_factors = np.array([2,3]).reshape(-1, 1)
scaled_a = a * scaling_factors
print(scaled_a)

[[ 60  54]
 [150 300]]


## Distance to Origin
Given an array of points(x,y coordinates),calculate the Euclidean distance of each point from the origin (0, 0) using broadcasting

In [13]:
import numpy as np

points = np.array([
    [5, 4],
    [2, 3],
    [1, 9],
    [2, 0], 
])

x = points[:, np.newaxis, :]
y = points[np.newaxis, :, :]

squared_diff = (x-y) ** 2

distances = np.sqrt(squared_diff.sum(axis=2))

print(f"Points:\n{points}")
print(f"Distances:\n{np.round(distances, 2)}")

Points:
[[5 4]
 [2 3]
 [1 9]
 [2 0]]
Distances:
[[0.   3.16 6.4  5.  ]
 [3.16 0.   6.08 3.  ]
 [6.4  6.08 0.   9.06]
 [5.   3.   9.06 0.  ]]
