## Creating Numpy Arrays

In [2]:
import numpy as np

In [5]:
# creating a 1D array from a list
my_list = [1,2,3,4,5]
print(my_list)
print(type(my_list))

my_array = np.array(my_list)
print(my_array)
print(type(my_array))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# Creating a 2D array from a list of lists
my_list_of_lists = [[1,2,3], [4,5,6], [7,8,9]]
my_2d_array = np.array(my_list_of_lists)
print(my_2d_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Specifying the data type
my_array_float = np.array(my_list, dtype=np.float64)
print(my_array_float)
print(my_array_float.dtype)

[1. 2. 3. 4. 5.]
float64


## Creating Array  with specific Values

In [9]:
# Creating an array of zeros and ones
zeros_array = np.zeros((3, 4))
ones_array = np.ones((2,3))
print(zeros_array)
print(ones_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# Creating an array fileed with 7s
full_array = np.full((2,2), 7)
print(full_array)

[[7 7]
 [7 7]]


In [11]:
# Creating an empty array (garbage value -> faster)
empty_array = np.empty((2, 2))
print(empty_array)

[[1.13779622e-313 0.00000000e+000]
 [4.66041296e-310 4.66041276e-310]]


## Creating Arrays with Sequences

In [12]:
# Creating an array with a range of values
arange_array = np.arange(0, 10, 2) # 2 is the step number
print(arange_array)

[0 2 4 6 8]


In [13]:
# Creating an array with evenly spaced values
linspace_array = np.linspace(0, 1, 5) # 5 is the no of elements we eant
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


## Creating Arrays with Random Values

In [14]:
# Creating an array with random values
random_array = np.random.rand(2, 3) # Value between 0 and 1
print(random_array)

[[0.50179377 0.77431559 0.53842102]
 [0.03914665 0.89288422 0.9424475 ]]


In [20]:
# Creating an array with random integers
random_int_array = np.random.randint(0, 10, (3, 3)) # low, high(exclusive), shape
print(random_int_array)

[[7 3 8]
 [7 1 1]
 [2 3 7]]


In [16]:
# Creating an array with random samples from the standard normal distribution
random_normal_array = np.random.randn(2,2)
print(random_normal_array)

[[-0.59258537  0.3823214 ]
 [ 1.10644697 -1.17846753]]


## Array Attributes

In [17]:
# Checking the number of dimensions
my_2d_array = np.array([[1,2,3], [4,5,6]])
print(my_2d_array.ndim)

my_1d_array = np.array([1,2,3])
print(my_1d_array.ndim)

2
1


In [19]:
# Checking the shape of the array
print(my_2d_array.shape)
print(my_1d_array.shape)

(2, 3)
(3,)


In [21]:
# The total number of elements in the array
print(my_2d_array.size)
print(my_1d_array.size)

6
3


In [22]:
# Checking the data type of the array
print(my_2d_array.dtype)

float_array = np.array([1.0, 2.0, 3.0])
print(float_array.dtype)

int64
float64


In [24]:
# CHecking the itemsize of the array
print(my_2d_array.itemsize)

float_array = np.array([1.0, 2.0, 3.0], dtype=np.float32)
print(float_array.itemsize)

8
4


In [25]:
# Checking the nbytes(bytes consumed by the elements of the array). [itemsize * size]
print(my_2d_array.nbytes)
print(float_array.nbytes)

48
12


# Exercises

In [26]:
# Create a 3x3 numpy array filed with the value 3.14
a1 = np.full((3,3), 3.14)
print(a1)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [28]:
# Create a Numpy array cotaining the even numbers from 20 to 40
a2 = np.arange(20, 41, 2)
print(a2)

[20 22 24 26 28 30 32 34 36 38 40]


In [31]:
# Generate a 4x4 NumPy array with random floating-point numbers between 0 and 1.
a3 = np.random.rand(4,4)
print(a3)

[[0.87917148 0.52861324 0.52787871 0.15900023]
 [0.07384222 0.14922061 0.78870941 0.63529567]
 [0.69799456 0.9061882  0.65259103 0.99088821]
 [0.15592277 0.7965201  0.38679751 0.70672863]]


In [33]:
# Create a 5x2 NumPy array with random integers between 1 and 10. Print
# its ndim, shape, size, dtype, itemsize, and nbytes

a4 = np.random.randint(1, 11, (5,2))
print(a4)
print(a4.ndim)
print(a4.shape)
print(a4.size)
print(a4.dtype)
print(a4.itemsize)
print(a4.nbytes)

[[10  3]
 [ 8 10]
 [ 6  1]
 [ 3 10]
 [ 6  9]]
2
(5, 2)
10
int64
8
80


In [38]:
# Create a NumPy array from the list [1,2,3,4,5] and explicity set the data type
# to np.int8. Verify the dtype anditemsize attributes
a5 = np.array([1,2,3,4,5])
print(a5)
print(f"Before dtype: {a5.dtype}")
print(f"Before itemsize: {a5.dtype}")
#a5 = np.array([1,2,3,4,5], dtype=np.int8)
a5_int8 = a5.astype(np.int8)
print(a5_int8)
print(f"After dtype: {a5_int8.dtype}")
print(f"After itemsize: {a5_int8.dtype}")


[1 2 3 4 5]
Before dtype: int64
Before itemsize: int64
[1 2 3 4 5]
After dtype: int8
After itemsize: int8
