## Creating Numpy Arrays

In [2]:
import numpy as np

In [5]:
# creating a 1D array from a list
my_list = [1,2,3,4,5]
print(my_list)
print(type(my_list))

my_array = np.array(my_list)
print(my_array)
print(type(my_array))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# Creating a 2D array from a list of lists
my_list_of_lists = [[1,2,3], [4,5,6], [7,8,9]]
my_2d_array = np.array(my_list_of_lists)
print(my_2d_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Specifying the data type
my_array_float = np.array(my_list, dtype=np.float64)
print(my_array_float)
print(my_array_float.dtype)

[1. 2. 3. 4. 5.]
float64


## Creating Array  with specific Values

In [9]:
# Creating an array of zeros and ones
zeros_array = np.zeros((3, 4))
ones_array = np.ones((2,3))
print(zeros_array)
print(ones_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# Creating an array fileed with 7s
full_array = np.full((2,2), 7)
print(full_array)

[[7 7]
 [7 7]]


In [11]:
# Creating an empty array (garbage value -> faster)
empty_array = np.empty((2, 2))
print(empty_array)

[[1.13779622e-313 0.00000000e+000]
 [4.66041296e-310 4.66041276e-310]]


## Creating Arrays with Sequences

In [12]:
# Creating an array with a range of values
arange_array = np.arange(0, 10, 2) # 2 is the step number
print(arange_array)

[0 2 4 6 8]


In [13]:
# Creating an array with evenly spaced values
linspace_array = np.linspace(0, 1, 5) # 5 is the no of elements we eant
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


## Creating Arrays with Random Values

In [14]:
# Creating an array with random values
random_array = np.random.rand(2, 3) # Value between 0 and 1
print(random_array)

[[0.50179377 0.77431559 0.53842102]
 [0.03914665 0.89288422 0.9424475 ]]


In [20]:
# Creating an array with random integers
random_int_array = np.random.randint(0, 10, (3, 3)) # low, high(exclusive), shape
print(random_int_array)

[[7 3 8]
 [7 1 1]
 [2 3 7]]


In [16]:
# Creating an array with random samples from the standard normal distribution
random_normal_array = np.random.randn(2,2)
print(random_normal_array)

[[-0.59258537  0.3823214 ]
 [ 1.10644697 -1.17846753]]


## Array Attributes

In [17]:
# Checking the number of dimensions
my_2d_array = np.array([[1,2,3], [4,5,6]])
print(my_2d_array.ndim)

my_1d_array = np.array([1,2,3])
print(my_1d_array.ndim)

2
1


In [19]:
# Checking the shape of the array
print(my_2d_array.shape)
print(my_1d_array.shape)

(2, 3)
(3,)


In [21]:
# The total number of elements in the array
print(my_2d_array.size)
print(my_1d_array.size)

6
3


In [22]:
# Checking the data type of the array
print(my_2d_array.dtype)

float_array = np.array([1.0, 2.0, 3.0])
print(float_array.dtype)

int64
float64


In [24]:
# CHecking the itemsize of the array
print(my_2d_array.itemsize)

float_array = np.array([1.0, 2.0, 3.0], dtype=np.float32)
print(float_array.itemsize)

8
4


In [25]:
# Checking the nbytes(bytes consumed by the elements of the array). [itemsize * size]
print(my_2d_array.nbytes)
print(float_array.nbytes)

48
12


# Exercises

In [26]:
# Create a 3x3 numpy array filed with the value 3.14
a1 = np.full((3,3), 3.14)
print(a1)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [28]:
# Create a Numpy array cotaining the even numbers from 20 to 40
a2 = np.arange(20, 41, 2)
print(a2)

[20 22 24 26 28 30 32 34 36 38 40]


In [31]:
# Generate a 4x4 NumPy array with random floating-point numbers between 0 and 1.
a3 = np.random.rand(4,4)
print(a3)

[[0.87917148 0.52861324 0.52787871 0.15900023]
 [0.07384222 0.14922061 0.78870941 0.63529567]
 [0.69799456 0.9061882  0.65259103 0.99088821]
 [0.15592277 0.7965201  0.38679751 0.70672863]]


In [33]:
# Create a 5x2 NumPy array with random integers between 1 and 10. Print
# its ndim, shape, size, dtype, itemsize, and nbytes

a4 = np.random.randint(1, 11, (5,2))
print(a4)
print(a4.ndim)
print(a4.shape)
print(a4.size)
print(a4.dtype)
print(a4.itemsize)
print(a4.nbytes)

[[10  3]
 [ 8 10]
 [ 6  1]
 [ 3 10]
 [ 6  9]]
2
(5, 2)
10
int64
8
80


In [38]:
# Create a NumPy array from the list [1,2,3,4,5] and explicity set the data type
# to np.int8. Verify the dtype anditemsize attributes
a5 = np.array([1,2,3,4,5])
print(a5)
print(f"Before dtype: {a5.dtype}")
print(f"Before itemsize: {a5.dtype}")
#a5 = np.array([1,2,3,4,5], dtype=np.int8)
a5_int8 = a5.astype(np.int8)
print(a5_int8)
print(f"After dtype: {a5_int8.dtype}")
print(f"After itemsize: {a5_int8.dtype}")


[1 2 3 4 5]
Before dtype: int64
Before itemsize: int64
[1 2 3 4 5]
After dtype: int8
After itemsize: int8


# Numpy Array Indexing and Slicing

In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

first_element = arr[0]
print(f"First element: {first_element}")

third_element = arr[2]
print(f"Third element: {third_element}")

last_element = arr[-1]
print(f"Last element: {last_element}")

second_to_last_element = arr[-2]
print(f"Second to last element: {second_to_last_element}")

First element: 10
Third element: 30
Last element: 50
Second to last element: 40


In [5]:
# Create a 2D Numpy Array
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

element_0_1 = arr_2d[0, 1]
print(f"Element at 0,1: {element_0_1}")

element_2_0 = arr_2d[2, 0]
print(f"Element at 2,0: {element_2_0}")

element_last_last = arr_2d[-1, -1]
print(f"Element at last row, last column: {element_last_last}")

Element at 0,1: 2
Element at 2,0: 7
Element at last row, last column: 9


## Indexing in Multidimensional array

In [6]:
arr_3d  = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])

element_0_1_0 = arr_3d[0, 1, 0]
print(f"Element at dimension 0, row 1, column 0: {element_0_1_0}")

element_1_0_1 = arr_3d[1, 0, 1]
print(f"Element at dimension 1, row 0, column 1: {element_1_0_1}")

Element at dimension 0, row 1, column 0: 3
Element at dimension 1, row 0, column 1: 6


## Understanding NumPy Array Slicing 

In [9]:
# arr[start:stop:step]
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# 2 inclusive 5 exclusive
slice_1 = arr[2:5]
print(f"Slice from index 2 to 5: {slice_1}")
# Slice from the beginning to index 4 (exclusive)
slice_2 = arr[:4]
print(f"Slice from the beginning to index 4: {slice_2}")

# Slice from index 6 to the end
slice_3 = arr[6:]
print(f"Slice from index 6 to the end: {slice_3}")

# Slice with a step of 2
slice_4 = arr[1:8:2]
print(f"Slice with a step of 2: {slice_4}")

# Slice the entire array with a step of 1 (creates a copy)
slice_5 = arr[:]
print(f"Slice of the entire array: {slice_5}")

# Reverse the array using a negative step
slice_6 = arr[::-1]
print(f"Reversed array: {slice_6}")

Slice from index 2 to 5: [30 40 50]
Slice from the beginning to index 4: [10 20 30 40]
Slice from index 6 to the end: [ 70  80  90 100]
Slice with a step of 2: [20 40 60 80]
Slice of the entire array: [ 10  20  30  40  50  60  70  80  90 100]
Reversed array: [100  90  80  70  60  50  40  30  20  10]


### Slicing in 2D Arrays

In [10]:
arr_2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Slice the first two rows and the first three columns
slice_1 = arr_2d[:2, :3]
print(f"Slice of first two rows and first three columns:\n{slice_1}")

# Slice all rows and columnds from index 1 onwards
slice_2 = arr_2d[:, 1:]
print(f"Slice of all rows and columnds from index 1 onwards:\n{slice_2}")

# Slice rows from index 1 onwards and the first two columns
slice_3 = arr_2d[1:, :2]
print(f"Slice of rows from index 1 onwards and the first two columns:\n{slice_3}")

# Slice with a step in both dimensions
slice_4 = arr_2d[::2, ::2]
print(f"Slice with a step of 2 in both dimensions:\n{slice_4}")

Slice of first two rows and first three columns:
[[1 2 3]
 [5 6 7]]
Slice of all rows and columnds from index 1 onwards:
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
Slice of rows from index 1 onwards and the first two columns:
[[ 5  6]
 [ 9 10]]
Slice with a step of 2 in both dimensions:
[[ 1  3]
 [ 9 11]]


## Understanding Views vs Copies

In [11]:
arr = np.array([10, 20, 30, 40, 50])

# Create a view using slicing
slice_view = arr[1:4]
print(f"Original array: {arr}")
print(f"Slice view: {slice_view}")

# Modify the view
slice_view[0] = 200
print(f"Modified slice view: {slice_view}")
print(f"Original array after modifying the view: {arr}")

# Create a copy using .copy()
slice_copy = arr[1:4].copy()
print(f"Slice copy: {slice_copy}")

# Modify the copy
slice_copy[1] = 300
print(f"Modified slice copy: {slice_copy}")
print(f"Original array after modifying the copy: {arr}")

Original array: [10 20 30 40 50]
Slice view: [20 30 40]
Modified slice view: [200  30  40]
Original array after modifying the view: [ 10 200  30  40  50]
Slice copy: [200  30  40]
Modified slice copy: [200 300  40]
Original array after modifying the copy: [ 10 200  30  40  50]


## Integer array indexing

In [14]:
arr = np.array([10, 20, 30, 40, 50])

indices = np.array([0, 2, 4])

selected_elements = arr[indices]
print(f"Selected elements: {selected_elements}")

arr[indices]= [100, 300, 500]
print(f"Modified array: {arr}")

Selected elements: [10 30 50]
Modified array: [100  20 300  40 500]


### 2D Integer array indexing

In [15]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

# create arrays of rows and columns indices
row_indices = np.array([0, 1, 2])
col_indices = np.array([0, 1, 2])

# Use integer array indexing to select elements
selected_elements = arr_2d[row_indices, col_indices]
print(f"Selected elements: {selected_elements}")

# Another example
row_indices = np.array([0, 0, 1, 2])
col_indices = np.array([1, 2, 0, 1])

selected_elements = arr_2d[row_indices, col_indices]
print(f"Selected elements: {selected_elements}")

Selected elements: [1 5 9]
Selected elements: [2 3 4 8]


## Boolean Array Indexing

In [16]:
arr = np.array([10, 20, 30, 40, 50])

# Create a boolean array (mask)
mask = np.array([True, False, True, False, True])

# Use boolean array indexing to select elements
selected_elements = arr[mask]
print(f"Selected elements: {selected_elements}")

# Modify elements using boolean array indexing
arr[mask] = [100, 300, 500]
print(f"Modified array: {arr}")


Selected elements: [10 30 50]
Modified array: [100  20 300  40 500]


### 2D Boolean Array Indexing

In [17]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

# Create a boolean array (mask)
mask = np.array([[True, False, True], [False, True, False], [True, False, True]])

# Use boolean array indexing to select elements
selected_elements = arr_2d[mask]
print(f"Selected elements: {selected_elements}")

arr_2d[mask] = [100, 300, 500, 700, 900]
print(f"Modified 2D array:\n{arr_2d}")

Selected elements: [1 3 5 7 9]
Modified 2D array:
[[100   2 300]
 [  4 500   6]
 [700   8 900]]


### Creating Boolean Masks

In [18]:
arr = np.array([10, 20, 30, 40, 50])

mask = arr > 25
print(f"Boolean mask: {mask}")

selected_elements = arr[arr>25]
print(f"Selected elements: {selected_elements}")

arr[arr>25] = 0
print(f"Modified array: {arr}")

Boolean mask: [False False  True  True  True]
Selected elements: [30 40 50]
Modified array: [10 20  0  0  0]


# Numpy Array Operations

## Element-wise operations

In [3]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

print(f"a+b: {a+b}")
print(f"a-b: {a-b}")
print(f"a*b: {a*b}")
print(f"a/b: {a/b}")
print(f"a//b: {a//b}")
print(f"a%b: {a%b}")
print(f"a**b: {a**b}")

c = 2 
print(f"a+c: {a+c}")
print(f"a*c: {a*c}")

a+b: [5 7 9]
a-b: [-3 -3 -3]
a*b: [ 4 10 18]
a/b: [0.25 0.4  0.5 ]
a//b: [0 0 0]
a%b: [1 2 3]
a**b: [  1  32 729]
a+c: [3 4 5]
a*c: [2 4 6]


In [6]:
a = np.array([1,2,3,4,5])
b = np.array([2,2,4,4,6])

print(f"a == b: { a==b }")
print(f"a != b: { a!=b }")
print(f"a > b: { a>b }")
print(f"a < b: { a<b }")
print(f"a >= b: { a>=b }")
print(f"a <= b: { a<=b }")

a == b: [False  True False  True False]
a != b: [ True False  True False  True]
a > b: [False False False False False]
a < b: [ True False  True False  True]
a >= b: [False  True False  True False]
a <= b: [ True  True  True  True  True]


In [7]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

print(f"np.logical_and(a, b): {np.logical_and(a,b)}")
print(f"np.logical_or(a, b): {np.logical_or(a,b)}")
print(f"np.logical_not(a): {np.logical_not(a)}")
print(f"np.logical_xor(a, b): {np.logical_xor(a,b)}")


np.logical_and(a, b): [ True False False False]
np.logical_or(a, b): [ True  True  True False]
np.logical_not(a): [False  True False  True]
np.logical_xor(a, b): [False  True  True False]


### Broadcasting
It allows NumPy to perform aithmetic operations on arrays with different shapes.

In [8]:
a = np.array([0, np.pi/2, np.pi])

print(f"np.sin(a): {np.sin(a)}")
print(f"np.cos(a): {np.cos(a)}")
print(f"np.exp(a): {np.exp(a)}")
print(f"np.log(np.array([1,2,3])): {np.log(np.array([1,2,3]))}")

np.sin(a): [0.0000000e+00 1.0000000e+00 1.2246468e-16]
np.cos(a): [ 1.000000e+00  6.123234e-17 -1.000000e+00]
np.exp(a): [ 1.          4.81047738 23.14069263]
np.log(np.array([1,2,3])): [0.         0.69314718 1.09861229]


In [10]:
a = np.array([1,2,3])
b = 2
print(f"a+b: {a+b}")

a+b: [3 4 5]


In [12]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([10, 20, 30])

print(f"a+b:\n{a+b}")


a+b:
[[11 22 33]
 [14 25 36]]


In [13]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10], [20]])

print(f"a+b:\n{a+b}")

a+b:
[[11 12 13]
 [24 25 26]]


In [15]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([10, 20])

try:
    print(a + b)
except ValueError as e:
    print(f"Error: {e}")

Error: operands could not be broadcast together with shapes (2,3) (2,) 


## Normalizing Data

In [16]:
data = np.array([[1,2,3], [4,5,6],[7,8,9]])
mean = data.mean(axis=0)
std=data.std(axis=0)

normalized_data = (data-mean)/std

print(f"Original Data:\n {data}")
print(f"Mean:\n{mean}")
print(f"Standard Deviation:\n{std}")
print(f"Normalized Data:\n{normalized_data}")

Original Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean:
[4. 5. 6.]
Standard Deviation:
[2.44948974 2.44948974 2.44948974]
Normalized Data:
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [17]:
# Apply a function to each row

matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
row_multiplier = np.array([1,2,3])

result = matrix * row_multiplier

print(f"Orgiinal Matrix:\n{matrix}")
print(f"Row Multiplier:\n{row_multiplier}")
print(f"Result:\n{result}")

Orgiinal Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row Multiplier:
[1 2 3]
Result:
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [ ]:
# Calculating Distances

points = np.array([[1,2], [3,4], [5,6]])

x = points[:, np.newaxis, :]
y = points[np.newaxis